(function() {var implementors = {};
implementors["hyper"] = [];
implementors["hyper_proxy"] = [{text:"impl&lt;C&gt; <a class=\"trait\" href=\"hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a> for <a class=\"struct\" href=\"hyper_proxy/struct.ProxyConnector.html\" title=\"struct hyper_proxy::ProxyConnector\">ProxyConnector</a>&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;C: <a class=\"trait\" href=\"hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a> + 'static,&nbsp;</span>",synthetic:false,types:["hyper_proxy::ProxyConnector"]},];
implementors["hyper_socks2"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a> for <a class=\"enum\" href=\"hyper_socks2/enum.Proxy.html\" title=\"enum hyper_socks2::Proxy\">Proxy</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/net/addr/trait.ToSocketAddrs.html\" title=\"trait std::net::addr::ToSocketAddrs\">ToSocketAddrs</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:false,types:["hyper_socks2::Proxy"]},];
implementors["hyper_tls"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a> for <a class=\"struct\" href=\"hyper_tls/struct.HttpsConnector.html\" title=\"struct hyper_tls::HttpsConnector\">HttpsConnector</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a>&lt;Error = <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;T::<a class=\"type\" href=\"hyper/client/connect/trait.Connect.html#associatedtype.Transport\" title=\"type hyper::client::connect::Connect::Transport\">Transport</a>: 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;T::<a class=\"type\" href=\"hyper/client/connect/trait.Connect.html#associatedtype.Future\" title=\"type hyper::client::connect::Connect::Future\">Future</a>: 'static,&nbsp;</span>",synthetic:false,types:["hyper_tls::client::HttpsConnector"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
